### ISSUE TITLE
Доработать страницу "Контакты" на сайтах г. Тюмень и Сочи

### ISSUE THREAD

**Issue by EAZYSHOP** [vgulaev/Thai-Lotus-Web#3]
Эта страница должна быть в едином формате.
- единый телефон
- ниже - салон с контактным номером и раскрытой картой. На карте должен быть такой масштаб, что виден один салон, но при отдалении карты на ней должны быть отмечены сразу все салоны
- ниже - другой салон с контактным номером и скрытой картой
- должна быть возможность раскрыть и скрыть карту
- карта интерактивна, нужно использовать сервис "Яндекс-карты"
- расстояние между блоками должны быть логически верными: между контактными данными салона и картой - небольшой отступ, от карты до контактных данных следующего салона - расстояние больше
- на картах должны быть корректные отметки

**Comment by movis08** [comment]
http://thailotus.ru/kontakty/1
