### ISSUE TITLE
Изменить порядок выбора городов

### ISSUE THREAD

**Issue by EAZYSHOP** [vgulaev/Thai-Lotus-Web#4]
-При заходе на поддомены sochi.thailotus.ru и chel.thailotus.ru город определяется автоматически по поддомену, не всплывает окно с выбором города
- При заходе на домен thailotus.ru в г. Тюмени, город автоматически определяется по ip-адресу, не всплывает окошко с выбором городов.
- При заходе на домен thailotus.ru в любом другом городе (кроме Тюмени) - всплывает окно с выбором городов
- Выбор города должен определяется на странице входа! После единоразового выбора города в пределах одной сессии запрос выбора города производится не должен.

**Comment by movis08** [comment]
Тест работы с геолокацией

**Comment by movis08** [comment]
Тест пройден

**Comment by movis08** [comment]
Работает. Обновить страницы через Ctrl+F5.
